### ISSUE TITLE
the bot doesnt respond 

### ISSUE THREAD

**Issue by bluezar54** [chxlls/economybot#14]
i downloaded all dependecies with node but the bot come online and doent trigger to the commands

**Comment by bluezar54** [comment]
could u contact me on discord : ) seed#6969

**Comment by bluezar54** [comment]
the log is thi (node:7344) UnhandledPromiseRejectionWarning: TypeError: Discord.RichEmbed is not a constructor
    at Object.module.exports.run (C:\Users\\Desktop\economybot-master\commands\help.js:8:17)
    at Client.<anonymous> (C:\User\Desktop\economybot-master\index.js:54:17)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\\Desktop\economybot-master\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\\Desktop\economybot-master\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\\Desktop\economybot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Desktop\economybot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\\Desktop\economybot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\\Desktop\economybot-master\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
(node:7344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TheFinality** [comment]
replace Discord.RichEmbed with Discord.MessageEmbed
